### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mini-turtle** [captn3m0/Scripts#2]
When I'm *not* using a file with a list of chapter names (ie the 2nd argument to the script) -- there is a bug with these lines:
```
    # If we are using a chapters.txt that is valid
    if ((CHAPTERS_TITLES_LENGTH >= CHAPTER_INDEX)) ; then
      CHAPTER_TITLE=${CHAPTERS[$CHAPTER_INDEX]}
    fi
```

It destroys *only* the 1st file/chapter name.
When I comment those lines out.. it works normally.

Thanks.

**Comment by captn3m0** [comment]
Thanks for reporting this. I'll take a look :soon:
